select * from "HPFM"."WDD1" where "WddCode" = '35305'



update "HPFM"."OWDD" set "Status" = 'N' where "WddCode" = '35305'



update "HPFM"."WDD1" set "Status" = 'N' where "WddCode" = '35305'



select *
---"USERID", "DATE", "IN", "OUT"
 from "DUBAILIMITEDINV"."ATT_PREIMPORTSH" WHERE "USERID" = '603672' order by "DATE"

UPDATE "DUBAILIMITEDINV"."ATT_PREIMPORTSH" SET "FIRSTNAME" =' ', "SHIFT" ='S001' WHERE "USERID" = '603672' and DATE = '20250602'

INSERT INTO "DUBAILIMITEDINV"."ATT_PREIMPORTSH" ("USERID","FIRSTNAME", "SHIFT", "DATE", "IN", "OUT")
VALUES('603672',' ','S001','20250602','7:25:35','17:25:35')


 DELETE FROM "DUBAILIMITEDINV"."ATT_PREIMPORTSH" WHERE "ID"='451661'



 -----------------------------------------------------------------------------
 Update OPRC T0 set T0."ValidTo"='20241231' where T0."PrcCode"  IN ('1 Nu Kit','AL BURQ','ALI SULT','ALM MAN','ALW CLN','ALW MAN','ALWSL CL','ALY CLN','ALY KIFA','ALY MAN','ALYKIFMP','BEL BIKE','BEL CIVI','BEL MAN','Bloom F','BLR MAN','BLUE RIB','Boom Car','BUTI MAN','Carwash','CLN CAMC','COMCLN','CW store','DAR AL A','DES DAC','DES MAN','DES MEP','DESC DC','DESC MAN','DESC MEP','DHA CL','DHA MAN','DIF CLN','DIFC HOS','DIFCCLNG','DLI LRY','DLI LYNX','DLI MEP','DLI WAR','DLI(LCL)','DLI-WRSN','DLIHOSP','DLY CLN','DP  DATA','DP  K&L','DP CLEAN','DP HOSPI','DP K9AWJ','DP LNDSC','DP MANPR','DP MEP','DPA','DPO CLN','DPO DAC','DPO HOS','DPO K9C','DPO KNL','DPO LAS','DPO MAN','DPO MEP','DPP CL','DUB HOS','DUC CLN','DUST MAN','DV024','DV025','DV026','DV027','DV028','DV029','DV030','DXBCOURT','FITOUT','GDR CLN','GDR LAS','GDR MEP','GDRFA','GDRFA CL','GDRFA LS','HAYT MAN','HP-PR-80','HPPR-809','HPPR-836','HPPR-841','HPPR-850','HPPR-870','HPS AWSL','IDF MEP','IDF Rack','IMGRTN','IMM MEP','LAD CAMC','LAS OTH','LEB CLN','LEB MEP','MBR DATA','MBRS CLN','MBRS MEP','MBRS_SG','NED CLN','NED LAN','NED MAN','NED MEP','NED SSC','NEDA MEP','NEDAA CL','NEDAA SS','NSIRA OB','NWSRA CL','PPD HOS','PPD MEP','PPD MEP1','PRJ00','PRJ0001','PRJ0002','PRJ0003','PRJ0004','PRJ0005','PRJ0006','PRJ0007','PRJ0008','PRJ0009','PRJ0010','PRJ0011','PRJ0012','PRJ0013','PRJ0014','PRJ0015','PRJ0016','PRJ0017','PRJ0018','PRJ0019','PRJ0020','PRJ0021','PRJ0022','PRJ0029','PRJ0030','PRJ0031','PRJ0032','PRJ0033','PRJ0034','PRJ0035','PRJ0036','PRJ0037','PRJ0038','PRJ0039','PRJ0040','PRJ0041','PRJ0042','SAL QUO','Saloon','SHA COS','SHARED','SIR CLN','SIR DAC','SIR HOS','SIR MEP','SIRA DC','SIRA MEP','SME -PRJ','SME MEP','SME PRJ','SME-MEP','SMTVLT','SQ','TDC CLN','TDW CLN','TDW CLNG','TDW MAN','TDW MEP','TDWCL CL','TLC CLN','TLT','TLT HOS','TLT MEP','TRU MAN','TSD CLN','TSD CLNG','TSD LAS','TSD LNDS','TSD MAN','TSD MEP','TSDMANPR','UXE MAN','WSL BIKE','WSL MAN','YLYS CL')

 ---------------------------------------------------------------------
 SELECT *  FROM OPRC T0 ---where T0."ValidTo" = '20241231'